### ISSUE TITLE
[BUG] Item Permissions not functioning in 1.11.2 

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGItems-reloaded#251]
Server version: 1.11.2 git-Spigot-3fb9945-2b6c9f4
RPGItems: `v3.5.262 for 1.11.2` and `v3.5.125 for 1.8`

Recently updated from 1.8 to 1.11.2 and while testing out some thigns, making sure it worked correctly, I gave a player one of our previous weapons that had a permission on it. 
In 1.8, this worked just fine, and anyone who had that item but lacked the permission node set on it were unable to use the item in question.
In 1.11, this does not work at ALL! Anyone who gets their hands on these items can use them, even if they do not have the permission set on it. 

Hopefully this can be fixed before my players figure it out...

Here is an example item which worked fine in 1.8, and only players who had the permission `rpgitem.infernalblade` were able to use it, but now *anyone* is allowed to:
````yaml
  infernal:
    name: infernal
    id: 895
    haspermission: true
    permission: rpgitem.infernalblade
    display: '&4&lＩＮＦＥＲＮＡＬ ＢＬＡＤＥ'
    quality: TRASH
    damageMin: 35
    damageMax: 35
    armour: 0
    type: Long Sword
    hand: Two Handed
    lore: Born from the hate, greed, and evil of humanity, this sword was created as Divinity Blade’s evil twin, mirroring it in both strength and magic ability. Unlike Divinity Blade, it was born from evil and darkness.
    description:
    - '&f&6&lSpecial Quest Item'
    - '&f&8&lBaneful Instrument'
    item: IRON_SWORD
    ignoreWorldGuard: false
    item_data: 0
    powers:
      '0':
        powerName: potionself
        cooldown: 1400
        amp: 2
        time: 200
        type: DAMAGE_RESISTANCE
        consumption: 0
      '1':
        powerName: potionhit
        chance: 33
        duration: 30
        amplifier: 0
        type: HARM
        consumption: 0
      '2':
        powerName: potionhit
        chance: 7
        duration: 200
        amplifier: 2
        type: SLOW
        consumption: 0
    recipechance: 6
    hasRecipe: false
    dropChances: {}
    hitCost: 1
    hittingCost: 1
    blockBreakingCost: 1
    hitCostByDamage: false
    maxDurability: -1
    defaultDurability: -1
    durabilityLowerBound: 0
    durabilityUpperBound: 250
    forceBar: false
    showPowerText: true
    showArmourLore: true
    damageMode: FIXED
    customItemModel: false
````
