### ISSUE TITLE
Name could not contain dot '.'

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#31]
When creating an item named 'some.thing' it splitted into 2 blocks:

```yaml
items:
  some:
    thing:
      name: some.thing
      id: 1
      haspermission: false
      display: some.thing
      quality: COMMON
...
```

Thus the config parsed with error and no items will be loaded.
