### ISSUE TITLE
Consider rewriting plugin

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGitems-reloaded#34]
Consider rewriting whole plugin and adapt to spigot-api-1.8.8
May solve these issues #8 #9 #21 #24
Could provide more clear codes and well-organized API.
Working on branch new-master
Any ideas?

**Comment by phoenixlzx** [comment]
A new API system that support script-like functionality, which let users write their own feature definitions.

E.g., a simple power definition could be:

```yaml
name: goldstick
desc: Right click on any block to make it a gold block, left click to break target into gold ingots.
on-rightclick: setblock @{target} gold_block
on-leftclick: destroy @{target}, drop gold_ingot x4
```

* `name` is the power name, which will be used in `items.yml`
* `desc` is description of the feature/power
* `on-{rightclick/leftclick}` is the action when clicking. We could add `on-hold` or `on-armored` or something like that.

Though it seems not easy to write a lexer for user defined scripts, let's make a JSON version:

```javascript
{
  "name": "goldstick",
  "desc": "Right click on any block to make it a gold block, left click to break target into gold ingots.",
  "on-rightclick": {
    "actions": [
      {
        "act": "setblock 41",
        "target": @{target}
      }
    ]
  },
  "on-leftclick": {
    "actions": [
      {
        "act": "destroy",
        "target": @{target}
      }, {
        "act": "drop",
        "item": "gold_ingot",
        "amount": 4
      }
    ]
  }
}
```

`actions` is a list of API call, which the plugin core provides. On plugin load/reload, all user defined features will be loaded into library and invoked when specific item is used.
